services:
  - type: web
    name: velvet-api
    env: docker
    dockerfilePath: ./services/api/Dockerfile
    dockerContext: ./services/api
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase:
          name: velvet-db
          property: connectionString
      - key: VELVET_SEED_RESET
        value: "false"

databases:
  - name: velvet-db
    plan: free
    databaseName: velvet
    user: velvet

