ALTER TABLE member_profiles
    ADD COLUMN IF NOT EXISTS height_cm INTEGER,
    ADD COLUMN IF NOT EXISTS job_title VARCHAR(120),
    ADD COLUMN IF NOT EXISTS education VARCHAR(120),
    ADD COLUMN IF NOT EXISTS languages VARCHAR(200),
    ADD COLUMN IF NOT EXISTS religion VARCHAR(80),
    ADD COLUMN IF NOT EXISTS looking_for VARCHAR(160);
